### ISSUE TITLE
Connection lost page should attempt a retry

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#119]
**Is your feature request related to a problem? Please describe.**

The connection lost screen after killing/relaunching the server appears as though it is trying to reconnect with the spinning icon:

![2022-09-16 16 28 10](https://user-images.githubusercontent.com/22067021/190825297-48717591-e300-4a8d-877d-48eef567f950.gif)

But it actually does nothing (as far as I can tell). So I have to refresh the page. 

**Describe the solution you'd like**

I'd like this to attempt to reconnect to my app and load when it's ready or not using this sort of misleading graphic

**Comment by jourdain** [comment]
So you are suggesting to have a different graphic in case of connection error?

(Just to be sure)

**Comment by banesullivan** [comment]
> So you are suggesting to have a different graphic in case of connection error?

Perhaps, but not quite.

I think this issue could go a couple of ways. The problem, IMO, is that this graphic is misleading about the behavior of the software. Rather than change the graphic, I'd like to change the behavior. However if we cannot change the behavior, then I think it is warranted to change the graphic.

IMO, this spinning graphic implies that the software is seeking a connection as spinning icons are ubiquitously used to indicate "loading". I would like for trame to implement some sort of functionality that attempts to reconnect to the app periodically while this icon is spinning such that the graphic's implication about what the software is doing is accurate/intuitive.

If this is too much work, then replacing the graphic with something more aligned with the "Connection lost" aspect of what it's trying to convey would be more appropriate. Something like (from random google image search):

![2463100-200](https://user-images.githubusercontent.com/22067021/191298216-ea43e4d5-54ea-4db8-8b43-713da36b5448.png)

**Comment by banesullivan** [comment]
Also, a bit nitpicky, but "Connection Close" feels off to me... I would advocate for "Connection Lost" or "Connection Close***d***"

**Comment by jourdain** [comment]
The reconnect can be done but could trigger side effect when cloud deployment is used. But some option could be done when using localhost?

In case of websocket we can either get a __close event__ or an __error event__. We just need to make sure to do a better job of conveying the proper message. The issue here is that I reused the loading widget to show error/close message rather than making a new widget for those.

**Comment by jourdain** [comment]
Added support for reconnect on `trame-client==2.4.0`. You can either add in the url a `?reconnect` and you will get the error message along with a button to let you try to reconnect, or if you do `?reconnect=auto`, the client will make 10 attempts to reconnect across 5 seconds.

**Comment by banesullivan** [comment]
I'm having trouble using these new features... Prior to `trame-client==2.4.0`, I could close my laptop and loos connection. Now, with `trame-client==2.4.0`, the view freezes (with or without the `reconnect` parameter) with no graphic or message about the connection status

**Comment by jourdain** [comment]
I guess you will have to show also I'm guessing the url you use is `...?ui=plot_id&reconnect` not `?ui=...?reconnect`?

**Comment by banesullivan** [comment]
Correct. `...?ui=plot_id&reconnect` and `...?ui=plot_id&reconnect=auto` both have the same effect for me (frozen view on disconnect). I'll look at this again tomorrow with fresh eyes to make sure I'm not messing something up

**Comment by banesullivan** [comment]
And the view freezes on disconnect now without the `reconnect` parameter
