### ISSUE TITLE
Possible add-on modules

### ISSUE THREAD

**Issue by jourdain** [Kitware/trame#12]
No particular order just ideas

- [x] [tabulator](http://tabulator.info/)
- [x] [Plotly charts](https://plotly.com/python/)
- [x] [ITK/VTK](https://itk.org/)
- [x] [xaitk](https://xaitk.org/)

**Comment by jourdain** [comment]
Checking tabulator as already supported via vuetify

**Comment by brunorpinho** [comment]
Hi @jourdain, thanks for implementing this tool. It is fantastic and it certainly will help a lot of devs and data scientists in the future. I was thinking that an integration with [panel](https://panel.holoviz.org/) would make trame even more powerful.

**Comment by jourdain** [comment]
Thanks for your suggestion. I guess we are still building some dev tools and infrastructure easily deploy such application. But if we still have some resources, we will certainly look into it. Thanks for your kind words @brunorpinho .

**Comment by cardinalgeo** [comment]
Hi all! Is it possible to integrate a viewer for a tile server (e.g., Bane's [`localtileserver`](https://github.com/banesullivan/localtileserver) or kitware's [`large_image`](https://github.com/girder/large_image)? For example, I'm imagining it taking the place of the `plotly` plot in [this](https://github.com/Kitware/trame/blob/a6659c9183d1d422a2e11bea492f9957dd782708/examples/06_vtk/Applications/RemoteSelection/app.py) `trame` example.

**Comment by banesullivan** [comment]
Hi @cardinalgeo! `localtileserver` is built on `large_image` so using/deploying either of the two is much the same! I actually made a demo of `large_image` and `trame` a few months back with the `trame-leaflet` module (https://github.com/Kitware/trame-leaflet). I'll dig up that code and post a reproducible example on GitHub somewhere ...stay tuned!

**Comment by cardinalgeo** [comment]
Awesome, thanks @banesullivan!

**Comment by banesullivan** [comment]
Here is a demo with large-image! This is also a great example of how to add custom REST endpoints to trame app: https://github.com/banesullivan/trame-tileserver

**Comment by cardinalgeo** [comment]
Sweet! I'll check it out in the next few days :)

**Comment by cardinalgeo** [comment]
> Here is a demo with large-image! This is also a great example of how to add custom REST endpoints to trame app: https://github.com/banesullivan/trame-tileserver

This works well — thanks @banesullivan!

**Comment by banesullivan** [comment]
I want to follow up on the original question posed by this issue and propose a [CesiumJS](https://cesium.com/platform/cesiumjs/) add-on module. 

Trame currently has the `trame-leaflet` module, which is working excellently (for the above example and) for 2D geospatial mapping. CesiumJS is a fantastic alternative for this sort of geospatial mapping with the addition of being 3D and supporting 3D Tiles. We've been using CesiumJS across a number of projects at Kitware, and I think it would be hugely impactful to couple with Trame.

FYI, decoupling CesiumJS from CesiumION is an easy hurdle to get over. Reference: https://gist.github.com/banesullivan/e3cc15a3e2e865d5ab8bae6719733752

**Comment by lalligagger** [comment]
@banesullivan CesiumJS would be a big draw for my use case! Considering trame after experimenting with some other frameworks (Dash and panel more recently).

**Comment by jourdain** [comment]
Seems pretty straight forward to integrate [vue cesium](https://zouyaoji.top/vue-cesium-v2/#/en/index)

**Comment by lalligagger** [comment]
I am not familiar with Vue or this wrapper, but took a look at the [v3 docs](https://zouyaoji.top/vue-cesium/#/en-US/component/quickstart). Here is a list of features that I'd have in mind:

- The current time of the viewer clock is accessible and can be forced to a certain time
- Update or get the current CZML datasource (GeoJSON also nice to support)
- Create/ update entities, primitives, image sources
- Access to click events in viewer (e.g. get lat/lon of clicked ellipsoid or selected entity)

I can find a vue cesium component for everything above except for the clock.

**Comment by jourdain** [comment]
vue-3 for trame is still WIP.

**Comment by jourdain** [comment]
- https://github.com/jp-liu/fit-screen
- https://github.com/tachibana-shin/vue-re-resizable
- https://vue-responsive-dash.netlify.app
