### ISSUE TITLE
`from trame.widgets import vtk` is not user friendly and should not be in the examples

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#127]
**Is your feature request related to a problem? Please describe.**

The `vtk` widgets module should be named something else as only serious VTK power users import vtk-python the proper way like `from vtkmodules.vtkRenderingCore import vtkRenderWindow`. 

Most (like 99% of) users simply use `import vtk` and that's not going anywhere. Having `from trame.widgets import vtk` in the examples where you want users to also use VTK-python is setting new users up for failure as the two namespaces will conflict. 

Further, VTK is an overwhelming library for new users, so seeing `from trame.widgets import vtk`, they will likely think that `vtk` is the actual `vtk` where they can get classes like `vtkPolyData` (actually even I thought that when first trying trame).

**Describe the solution you'd like**

The vtk widgets module should be named something other than `vtk`, like `vtk_widgets`

`from trame.widgets import vtk` should be something else, perhaps `from trame.widgets import vtk_widgets`

**Describe alternatives you've considered**

An alternative is to have all the examples use an alias: `from trame.widgets import vtk as vtk_widgets`

**Additional context**

I'm having to carefully modify this import statement in every trame app I create from the examples (I use the examples as templates which I expect most others do as well)

**Comment by jourdain** [comment]
I will be fine doing `from trame.widgets import vtk as vtk_widgets` in all examples as I would not like the redundancy of widgets be forced on everyone. 

In other word, that would means that every `trame.widgets.*` would need to be prefixed with `widgets_*`. Think plotly, matplotlib, leaflet and more...

**Comment by jourdain** [comment]
Also a side note, I usually encourage people to do the vtk import as follow when they don't want to deal with `vtkmodules`.

```python
from vtk import (
  vtkPolyData,
  vtkActor, 
  vtkMapper,
)
```

**Comment by jourdain** [comment]
So should we update the examples?

**Comment by banesullivan** [comment]
>I will be fine doing from trame.widgets import vtk as vtk_widgets in all examples

Let's do this in the examples with VTK then

> In other word, that would means that every trame.widgets.* would need to be prefixed with widgets_*. Think plotly, matplotlib, leaflet and more...

yeah... I too do not want to add a `*_widgets` suffix to each module so perhaps just aliasing the VTK one makes the most sense
