### ISSUE TITLE
app_local_view.py---------the `nodes_bytes` and `elems_bytes` are `list`s, not `bytes` 

### ISSUE THREAD

**Issue by hongbiaozhu** [Kitware/trame#144]
**Describe the bug**
In lines 86-87 of the 'https://github.com/Kitware/trame/blob/releasev1/examples/VTK/Applications/FiniteElementAnalysis/app_local_view.py'
the `nodes_bytes` and `elems_bytes` are `list`s, not `bytes` 

and I insert some code after line 88 to make it runable

**To Reproduce**

1. Go to 'https://github.com/Kitware/trame/blob/release-v1/examples/VTK/Applications/FiniteElementAnalysis/app_local_view.py', 
2. select data in 'https://github.com/shkiefer/dash_vtk_unstructured/tree/main/data' on Trame
![image](https://user-images.githubusercontent.com/49604228/200471820-c148d0e8-d86f-466a-a8a1-54cdd9b6b9a7.png)
3. See error
![image](https://user-images.githubusercontent.com/49604228/200471727-99a6dbba-a047-460f-808d-5c03b2498251.png)

***Code***
the inserted code in line 88, which joint the `bytes` in the lists
```python
     if type(nodes_bytes) ==list:
        a = b''
        for i in range(len(nodes_bytes)):
            a += nodes_bytes[i]
        nodes_bytes = a

    if type(elems_bytes) ==list:
        b = b''
        for i in range(len(elems_bytes)):
            b += elems_bytes[i]
        elems_bytes = b
```

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

***Trame:***

- [ ] Version 1.x
- [x] Version 2.x

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [x] MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

***py-web-vue version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
You are pointing to the version 1 of the code. The version 2 has been updated as you can see [here](https://github.com/Kitware/trame/blob/master/examples/06_vtk/Applications/FiniteElementAnalysis/app_local_view.py#L89-L93). 

Also [that example](https://github.com/Kitware/trame/blob/master/examples/00_howdoi/upload.py#L7) show how to use a helper class for uploaded files to prevent that separation of bytes or list of bytes.
