### ISSUE TITLE
Can not forward events without a current renderer on the interactor

### ISSUE THREAD

**Issue by Brandon-Xu** [Kitware/trame#154]
**Describe the bug**
Hi, I found a bug, but it doesn't have to happen on every machine any times,
Sometimes it works, sometimes throw this: **Can not forward events without a current renderer on the interactor**.
I has test many times many way by variable of control, but still can not find a pattern.
As I know, one colleagues of mine run the program in terminal, never throw this bug.
But another colleague of mine need run the program by java thread, this bug happend by this way, but sometimes it works.
So we try to run the program in the same machine in terminal, as my first colleagues, he never got this bug, but it still throw in our machine!

I google this message, found this.
![fa7141a1db04347c33a97ac57b08c58](https://user-images.githubusercontent.com/2850261/203324093-2befbddf-6bad-4a4d-9d57-5af20695d573.jpg)

But I can not imagine why getCurrentRenderer() dont work well.
So, I came here, hoping for some possible leads, maybe can help.

sorry for my english, I come from china. I hope I've described it correctly

***Code***

```python
# just same as examples
```

**Screenshots**
![e0e42c575f19fb9f465e1e3359bab77](https://user-images.githubusercontent.com/2850261/203319164-6285df25-7b99-4e66-89f1-87566eabfc01.png)

**Platform:**
Windows 10

***Trame:***
- [*] Version 2.x

***Device:***

- [*] Desktop
- [ ] Mobile

***OS:***

- [*] Windows

***Browsers Affected:***

- [*] Chrome

**Comment by jourdain** [comment]
This issue was introduced on `trame-vtk==2.0.9` as its shared state now is an incremental one. I still have to figure out what is the best way to handle that part. But if you are not affected by the add/remove actor, you should stick to `trame-vtk==2.0.8`.

**Comment by Brandon-Xu** [comment]
What do you mean by "its shared state now is an incremental one"? Will it cause some times the model cannot be loaded? So the only solution by far is to use `trame-vtk=2.0.8`, right?
I'm new to vtk and not familiar with some terminologies. What do you mean by "if you are not affected by the add/remove actor". It seems that if I use version 2.0.8, some functionality I cannot use, right?

**Comment by Brandon-Xu** [comment]
By the way, thanks for the tip, our script works well

**Comment by Jimmy-KL** [comment]
@jourdain I met a similar problem but I think I was affected by the add/remove actor problem. I'm using pyvista and it has a method to wrap the pyvista actor to vtk actor. At first, I thought it's a bug of pyvista (issue reported [here](https://github.com/pyvista/pyvista/pull/3385#issuecomment-1326196452)). Now I think it's the problem you mentioned here. Then I update the trame-vtk to version 2.0.9, unfortunately, I got the same problem in this issue that the model is not loaded.

**Comment by jourdain** [comment]
The issue is related to a double update which make the delta state "nothing".
