### ISSUE TITLE
Patch VTK's `serializeInstance` to change `print` statements to warnings

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#167]
`serializeInstance` in `Web/Python/vtkmodules/web/render_window_serializer.py` of VTK uses `print` statements to issue warnings. We should patch this in trame to use warnings so as to have better outputs than:

![Screen Shot 2022-12-14 at 11 07 33 AM](https://user-images.githubusercontent.com/22067021/207673070-15664b32-7dd5-4557-b23e-b0859ef9ec1d.png)

Further, I'm wondering if we want to add a flag to suppress these warnings?

**Comment by jourdain** [comment]
Is that fix with vtk==9.2.5 ?

**Comment by banesullivan** [comment]
Yes, it is
