### ISSUE TITLE
Template slot extension issue

### ISSUE THREAD

**Issue by Guarouba** [Kitware/trame#171]
**Describe the bug**

I am trying to reproduce a simple vuetify code to extends the tool bar with tabs. However using trame produce different result. The app bar gets override by the template slot extension. I suppose the issue is with "v_slot = 'extension'".

**To Reproduce**
I found this code on internet to add tabs to the App bar in vuetify:
```javascript
<template>
  <v-app>
    <v-app-bar app color="primary" dark>
      <v-app-bar-nav-icon> </v-app-bar-nav-icon>
      <v-toolbar-title>Coding Beauty</v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn icon>
        <v-icon>mdi-magnify</v-icon>
      </v-btn>
      //[...]
      <template v-slot:extension>
        <v-tabs align-with-title>
          <v-tab>Tab 1</v-tab>
          <v-tab>Tab 2</v-tab>
          <v-tab>Tab 3</v-tab>
        </v-tabs>
      </template>
    </v-app-bar>
  </v-app>
</template>

<script>
export default {
  name: 'App',
};
</script>
```
I translated it in python with Trame:
***Code***

```python
from trame.app import get_server
from trame.ui.vuetify import VAppLayout
from trame.widgets import vuetify

# -----------------------------------------------------------------------------
# Trame setup
# -----------------------------------------------------------------------------

server = get_server()

# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

# Main page content
with VAppLayout(server) as layout:
    with vuetify.VAppBar(app=True, color='primary', dark=True) as toolbar:
        vuetify.VAppBarNavIcon()
        vuetify.VToolbarTitle('Test')
        vuetify.VSpacer()
        with vuetify.VBtn(icon=True):
            vuetify.VIcon("mdi-magnify")
        # [...]
        with vuetify.Template(v_slot='extension'):
            with vuetify.VTabs(align_with_title=True):
                vuetify.VTab("Tab 1")
                vuetify.VTab("Tab 2")
                vuetify.VTab("Tab 3")
```

**Expected behavior**

![Screenshot from 2023-01-03 13-36-03](https://user-images.githubusercontent.com/23635069/210358489-d897639a-ba7e-4fe2-a659-2b0e2c5360b7.png)

**Obtained result**
![Screenshot from 2023-01-03 13-37-58](https://user-images.githubusercontent.com/23635069/210358764-daa37dd6-fe18-4d55-9259-4138989df9bb.png)

**Platform:**

***Trame:***

- [ ] Version 1.x
- [x] Version 2.x

***Device:***

- [ ] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [ ] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [ ] Chrome
- [x] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [x] Brave
- [ ] IE 11

***py-web-vue version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
So the translation to Python/trame should be `vuetify.Template(v_slot_extension=True)`.

Also to validate that your template/layout match your expectation, you can run the following to validate part of the template

```python
from trame.widgets import vuetify

print(vuetify.Template(v_slot='extension').html)
print(vuetify.Template(v_slot_extension=True).html)
```

**Comment by jourdain** [comment]
@Guarouba  can you confirm that fixed your issue?

**Comment by Guarouba** [comment]
Yes, it works as expected ! Thanks for the support.
