### ISSUE TITLE
GitTree Bug when change the active state

### ISSUE THREAD

**Issue by Jimmy-KL** [Kitware/trame#177]
**Describe the bug**

When I tried to use trame widget GitTree, I found that if I refresh the web browser, the state of the GitTree will change to the initial state. So I tried to store the status of the GitTree to the state of the server, then I found it seems there is a bug when changing the active state of the GitTree.

**To Reproduce**

1. Change the visibility of the 1st element.
2. Click on the 3rd element. Actually, any element except the currently active element).
3. The visibility of the 1st element will be changed. Only the last changed visibility will be changed.
4. Refresh the web browser, the visibility of the 1st element will change to the correct status.

***Code***
Here is a sample code modified from the [GitTree example](examples/04_trame-components/02_git_tree.py).

```python
from trame.app import get_server
from trame.ui.vuetify import VAppLayout
from trame.widgets import trame

selection_t = ["2"]
tree = [
    {"id": "1", "parent": "0", "visible": 0, "name": "Wavelet"},
    {"id": "2", "parent": "1", "visible": 0, "name": "Clip"},
    {"id": "3", "parent": "1", "visible": 1, "name": "Slice"},
    {"id": "4", "parent": "2", "visible": 1, "name": "Slice 2"},
]
server = get_server()
state = server.state

def visibility_change(event):
    _id = event["id"]
    _visibility = event["visible"]
    if _id == "1":  
        state.tree[0]['visible'] = int(_visibility)
    elif _id == "2":  
        state.tree[1]['visible'] = int(_visibility)
    elif _id == "3":
        state.tree[2]['visible'] = int(_visibility)
    elif _id == "4":
        state.tree[3]['visible'] = int(_visibility)
        
def actives_change(ids):
    _id = ids[0]
    if _id == "1":
        state.selection = [_id]
    elif _id == "2":  
        state.selection = [_id]
    elif _id == "3":  
        state.selection = [_id]
    elif _id == "4":
        state.selection = [_id]

with VAppLayout(server):
    trame.GitTree(
        sources=("tree", tree),
        actives=("selection", selection_t),
        visibility_change=(visibility_change, "[$event]"),
        actives_change=(actives_change, "[$event]"),
    )

if __name__ == "__main__":
    server.start()
```

**Expected behavior**

When I change the active of the GitTree, the last changed visibility of the element will not be changed.

**Screenshots**
Initial state:
![image](https://user-images.githubusercontent.com/114913030/211186886-9e95634a-717a-4f0b-85af-c4db548c8aac.png)
Change the visibility of the 1st element:
![image](https://user-images.githubusercontent.com/114913030/211186901-67be40d4-43b1-4f97-8474-18f70db0249e.png)
Click on the 3rd element:
![image](https://user-images.githubusercontent.com/114913030/211186945-59f31eee-eccc-41a3-9575-abe4a8b960e4.png)

**Platform:**

***Trame:***

- [ ] Version 1.x
- Version 2.x

***Device:***

- Desktop
- [ ] Mobile

***OS:***

- Windows
- [ ] MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- Chrome
- [ ] Firefox
- Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

***py-web-vue version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
You are just missing [`state.dirty("tree")`](https://trame.readthedocs.io/en/latest/core.state.html#trame_server.state.State.dirty) at the end of `def visibility_change(event):` method.

**Comment by Jimmy-KL** [comment]
> You are just missing [`state.dirty("tree")`](https://trame.readthedocs.io/en/latest/core.state.html#trame_server.state.State.dirty) at the end of `def visibility_change(event):` method.

Yes, that's the reason. Thanks!
