### ISSUE TITLE
App freezes on disconnect when template_name is used

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#179]
**Describe the bug**

Trame apps freeze on disconnect whenever a `template_name` is used. If using the `?reconnect` URL option, the button will never appear and the page becomes unresponsive. The issue is most notable with VTK apps but also happens for more simple apps like `examples/02_vuetify/01_menu.py`

**To Reproduce**

***Code***

Take the follow diff for `examples/02_vuetify/01_menu.py`

```diff
diff --git a/examples/02_vuetify/01_menu.py b/examples/02_vuetify/01_menu.py
index e935488..22d7d10 100644
--- a/examples/02_vuetify/01_menu.py
+++ b/examples/02_vuetify/01_menu.py
@@ -27,7 +27,7 @@ def print_item(item):

 state.trame__title = "Menu example"

-with SinglePageLayout(server) as layout:
+with SinglePageLayout(server, template_name="myapp") as layout:
     with layout.toolbar:
         vuetify.VSpacer()
         with vuetify.VMenu():
```

```bash
python examples/02_vuetify/01_menu.py --server
```

Then go to the URL:

```
http://localhost:8080/index.html?reconnect&ui=myapp
```

**Expected behavior**

On disconnect (closing/reopening my laptop does the trick), I expect to see the reconnection button due to the `?reconnect` URL option

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

***Trame:***

```
$ pip list | grep trame
trame                         2.2.5
trame-client                  2.4.0
trame-components              2.0.4
trame-deckgl                  2.0.1
trame-markdown                2.0.2
trame-matplotlib              2.0.1
trame-plotly                  2.0.1
trame-rca                     0.3.0
trame-router                  2.0.1
trame-server                  2.7.0
trame-simput                  2.1.0
trame-vega                    2.0.2
trame-vtk                     2.0.13
trame-vuetify                 2.0.2
```

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [x] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [x] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

***py-web-vue version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
Should be fixed by https://github.com/Kitware/trame-client/releases/tag/v2.4.1
