### ISSUE TITLE
User testimonial

### ISSUE THREAD

**Issue by jourdain** [Kitware/trame#18]
The goal of this issue is to capture positive feedback from the community so we can feature them on our web site.

- It is an opportunity for us to learn what you are doing with Trame and what made trame special for you.
- It is an opportunity for you to say thank you to the dev team. They love hearing what you have been up to and what you enjoyed about trame. That help motivate them.

Feel free to share comments, links, pictures, video, social media posts.

And thank you again for sharing your experience!

**Comment by banesullivan** [comment]
Perhaps this could also be a pinned discussion topic to get more traffic/visibility?

**Comment by jourdain** [comment]
Replacing this issue by https://github.com/Kitware/trame/discussions/new?category=show-and-tell
