### ISSUE TITLE
VtkRemoteLocalView local view not syncing

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#180]
**Describe the bug**

`examples/06_vtk/02_ContourGeometry/DynamicLocalRemoteRendering.py` is not updating the local view when the isovalue slider is changed

**To Reproduce**

3. See error

***Code***

```bash
python examples/06_vtk/02_ContourGeometry/DynamicLocalRemoteRendering.py
```

**Expected behavior**

I expect the local view to sync when the contour/isovalue is updated

**Screenshots**

https://user-images.githubusercontent.com/22067021/212418240-daa3d240-f688-4597-9c31-97cd26abaefd.mov

**Platform:**

***Trame:***

- [ ] Version 1.x
- [x] Version 2.x

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [x] MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

***py-web-vue version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
This was the missing line https://github.com/Kitware/trame/blob/master/examples/06_vtk/02_ContourGeometry/DynamicLocalRemoteRendering.py#L127

**Comment by banesullivan** [comment]
Ah, simple enough! Thanks!
