### ISSUE TITLE
Add `__version__` attribute to Trame packages

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame#183]
```py
>>> import trame
>>> trame.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'trame' has no attribute '__version__'
>>>
```

None of the Trame packages have a version attribute which makes it a bit difficult to dynamically tell which version of trame is installed. 

This can be implemented in a handful of ways as not to have to hardcode the version string. For example:

```py
from pkg_resources import DistributionNotFound, get_distribution

try:
    __version__ = get_distribution("trame").version
except DistributionNotFound:  # pragma: no cover
    # package is not installed
    __version__ = None
```

Or as a user, I could:

```py
>>> from pkg_resources import get_distribution
>>> get_distribution('trame')
trame 2.2.5 (/opt/miniconda3/envs/pyvista-dev/lib/python3.9/site-packages)
>>> get_distribution('trame').version
'2.2.5'
>>>
```

But having a `__version__` attribute is pretty standard and expected in Python packaging

**Comment by psavery** [comment]
So, adding a `__version__` is in general easy to do. But `trame.__version__` is a little harder. That's because we set up `trame` as a namespace package, and the root trame `__init__.py` is not supposed to contain anything other than the `__path__` extension (if it does contain anything else, the additional code is not guaranteed to be executed).

We did this mainly so that `trame.widgets`, `trame.modules`, and `trame.ui` could more easily be namespace packages as well.

Is it acceptable to have the root `__version__` somewhere else? Or should we look into making `trame.__version__` possible?

**Comment by jourdain** [comment]
Not sure of the benefit of having a version on trame itself.

**Comment by banesullivan** [comment]
> But trame.__version__ is a little harder. That's because we set up trame as a namespace package, and the root trame __init__.py is not supposed to contain anything

Oh weird... But there is a `__license__` there:

https://github.com/Kitware/trame/blob/28184737d7712f9ffe749ac3543bf3b43f4200fd/trame/__init__.py#L3

```py
>>> import trame
>>> trame.__license__
'Apache License 2.0'
```

I don't see any issues with adding a `__version__` there too

> Is it acceptable to have the root __version__ somewhere else?

You can put it anywhere so long as it's accessible from the top-level namespace of the package (i.e., `trame.__version__`)


> Not sure of the benefit of having a version on trame itself.

Well, the `trame` package isn't empty... At the end of the day I don't *need* the `__version__` on any of these packages but having it is really nice when debugging.

**Comment by banesullivan** [comment]
Thanks for the clarification, @psavery! This namespacing magic making more sense to me now. 

If you can get away from `trame` being a namespace package and there are justifications beyond me asking for a `__version__` attribute, great! If not, I don't want to request a chunk of work for this as there are plenty of other, fine ways to get the package version

**Comment by banesullivan** [comment]
> From the Python point of view, that may seems strange, 

Seems very strange to me and scares me a bit...

**Comment by jourdain** [comment]
But that part should be totally transparent to the user and in fact the user should not care about it.

**Comment by banesullivan** [comment]
Ahh, thanks for that analogy that, indeed, would be really nice and not all that strange.

**Comment by psavery** [comment]
> I'm not against having version on trame itself, but the benefit of it will be limited. The 2 key components are server and client. So having a version on them will be much more impactful. Also I'm envisioning runtime client version which mean it can't necessarily be figured out from the packaged installed. What I mean, is I see the possibility to have 2 client version installed and at runtime we could choose one vs the other... From the Python point of view, that may seems strange, but for the web point of view not that much. We are just serving different set of files...

So, for the Python versions, will they be located at `trame_server.__version__` and `trame_client.__version__`? We could have a `__version__` for every `trame-*` package like this.

Would the runtime client version be something different, like `trame_client.__runtime_version__`?

**Comment by jourdain** [comment]
So, I think we should have `trame-xxx.__version__` but for the runtime it will be something more related to the server instance. Not sure yet, but having something along those lines `server.client_version => trame-client-vue3@1.2.3`

**Comment by jourdain** [comment]
Also it could be nice if we could have that version info on `trame.[modules|widgets|ui].[vuetify|client|...].__version__`

**Comment by jourdain** [comment]
Just ideas so far, no real direction on where we should be going...

**Comment by psavery** [comment]
> Also it could be nice if we could have that version info on `trame.[modules|widgets|ui].[vuetify|client|...].__version__`

Yes, we can do that too!

**Comment by jourdain** [comment]
We just need to see if it is that useful.

**Comment by psavery** [comment]
Okay, `trame_server` and `trame_client` now both have `__version__` on them.

Now let's take `trame-vtk` as an example for how we will be doing every other `trame-*` project.

We can add this to `trame_vtk/__init__.py`:

```python
from trame_client.utils.version import get_version

__version__ = get_version("trame-vtk")
```

Then anywhere else we want to add it in the project, we can do something like this:
```python
from trame_vtk import __version__
```

And the `__version__` will be exposed in that file. So I guess we should decide if we want this on every module, ui, and widget file.

**Comment by psavery** [comment]
Okay, `__version__` has been added now to most of the trame packages (including the cookiecutter). I did not yet expose it, however, in the `module`/`ui`/`widget` files. So for instance, right now, you can get the trame VTK version via `from trame_vtk import __version__`, but you couldn't get it via `from trame.widgets.vtk import __version__`.

Is that something we want to add right now, or revisit later?

**Comment by larsoner** [comment]
Can we reopen this since `trame` itself does not seem to have `__version__` at least with the latest pip installed version?
```
$ pip list | grep trame
trame                         3.2.4
trame-client                  2.11.2
trame-server                  2.11.7
trame-vtk                     2.5.8
trame-vuetify                 2.3.1
$ python -c "import trame; print(trame.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'trame' has no attribute '__version__'
```

**Comment by larsoner** [comment]
Ahh I see above:

> So as long as the root trame module is a namespace package, it should not contain any extra code, including a __version__.

FWIW this is surprising behavior to me (and probably others in the scientific python ecosystem) but feel free to keep closed as wontfix if you prefer!

**Comment by psavery** [comment]
@larsoner I think `from trame import __version__` would be nice to have! But I'm not sure if it's possible since we have it as a namespace package. I'm open to suggestions, though.

I also wonder what other projects that have a root namespace package do about things like `__version__`.
