### ISSUE TITLE
`trame-client` not generating `index.html`

### ISSUE THREAD

**Issue by Besler** [Kitware/trame#204]
**Describe the bug**

Following the [cookiecutter](https://github.com/Kitware/trame-cookiecutter), the file `index.html` is not output when building the docker image, resulting in a failure of the Apache server to serve files.

One can see this in the `build_image.sh` output:

```bash
[...]
usage: app.py [-h] [--name NAME] [--input INPUT]

HTML app file generator for trame applications

optional arguments:
  -h, --help     show this help message and exit
  --name NAME    Application name to encode inside HTML {name}.html
  --input INPUT  Input file to use as template
usage: app.py [-h] [--name NAME] [--input INPUT]

HTML app file generator for trame applications

optional arguments:
  -h, --help     show this help message and exit
  --name NAME    Application name to encode inside HTML {name}.html
  --input INPUT  Input file to use as template
  [...]
  ```
Indicating `trame.tools.www` is failing.

If one force pins `trame-client` to `2.5.1`, it starts to work. See [`trame client v2.5.1`](https://github.com/Kitware/trame-client/blob/v2.5.1/trame_client/module/__init__.py) to [`trame client v2.6.0`](https://github.com/Kitware/trame-client/blob/v2.6.0/trame_client/module/__init__.py), the switch for `vue2` and `vue3` was added. Maybe the issue is me and I need to set `server.client_type` to either `vue2` or `vue3`?

`client_type` does appear to be set when I load a server:

```python
>>> from trame.app import get_server
>>> server = get_server()
>>> print(server.client_type)
vue2
```

**To Reproduce**

Run [trame cookiecutter](https://github.com/Kitware/trame-cookiecutter).

1. `cookiecutter gh:kitware/trame-cookiecutter` # Just App, no component
1. `cd deploy/docker`
1. `./scripts/build_image.sh`
1. `./scripts/run_image.sh`
1. go to `localhost:8080` and see the Apache error page

***Code***

N/A

**Expected behavior**

Hitting the port loads the webpage.

**Screenshots**

<img width="399" alt="Screenshot 2023-02-13 at 9 21 51 PM" src="https://user-images.githubusercontent.com/19190951/218646734-ae10a58e-deef-4b0d-bb84-e1097b2736d1.png">

**Platform:**

***Device:***

- [X] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [ ] MacOS
- [X] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [X] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

**Comment by jourdain** [comment]
Thanks for bringing that up... I think I know why since I removed the auto-loading of the client to allow it to be deferred once we know which version is actually activated and move that logic to the `server.start()`. So now the `trame.tools.www` is missing that client initialization all together... ;-)

**Comment by jourdain** [comment]
Actually it was a bit more complicated. The `trame.tools.www` was only looking for file to serve and was skipping the `module.setup` path which is now use to figure out which vue2/3 code we want to enable... 

Anyway, thanks again for reporting such issue...
