### ISSUE TITLE
`${HOST}:${PORT}/favicon.ico` should return `server.stat.trame__favicon`

### ISSUE THREAD

**Issue by Besler** [Kitware/trame#207]
**Is your feature request related to a problem? Please describe.**

Would it be possible for `/favicon.ico` to return the value from `server.stat.trame__favicon`? Seems pedantic, but I believe this is standard in web development?

**Describe the solution you'd like**

Going to `/favicon.ico` returns the favicon set with `server.stat.trame__favicon`.

This probably requires `trame-router` in the application by default. I guess the simplest solution would be to provide another template in `trame-vuetify` similar to `VAppLayout` that routes `/favicon.ico`.

**Describe alternatives you've considered**

Just not implementing this feature.

**Additional context**

None.

**Comment by jourdain** [comment]
Why do you need an HTTP endpoint for that favicon? Especially since trame let you define it?

**Comment by jourdain** [comment]
Trame let you create new routes/handler which can be use to provide such favicon.

**Comment by jourdain** [comment]
Also, if you use docker, the website get generated statically which means that you can drop your favicon there as well...

**Comment by Besler** [comment]
Okay - will provide in my code either through a router or the apache server. I only ask because it seems to be standard.

https://facebook.com/favicon.ico
https://github.com/favicon.ico

**Comment by jourdain** [comment]
But each trame app is a standalone process and not a regular web server. 
When used for multi-user setup (inline with std web server), the content is served by an Apache in docker, so you can drop your favicon there without any change or expectation from trame. 

Then each trame app deployed in that docker can dynamically override it and even change it during the application execution.

**Comment by Besler** [comment]
Excellent point - I will just do that. Thanks Sebastien.
