### ISSUE TITLE
How can trame be deployed in an environment with no desktop or graphical interface, such as k8s

### ISSUE THREAD

**Issue by haoxl3** [Kitware/trame#333]
How can trame be deployed in an environment with no desktop or graphical interface, such as k8s

[x] unbuntu
[x] arm64

**Comment by jourdain** [comment]
I don't understand the question, as trame does not require a desktop or graphic interface.

Are you asking that question for VTK? If that is the case, you need a special build of VTK for offscreen purposes, assuming you are doing "rendering" within VTK.  For that, you can either use OSMesa or EGL if you aim to leverage a GPU for faster performance. 

Closing, as it is not an issue, and on top of that, it is not trame related.
