### ISSUE TITLE
hot reload for UI, controller and state change won't work

### ISSUE THREAD

**Issue by bourdaisj** [Kitware/trame#455]
**Describe the bug**
I can't get the hot reload feature to work for controller function, UI and state change. However, the trame_server.utils.hot_reload.hot_reload decorator works fine.

EDIT: 17_dev_reload example works fine, with a few updates, see here: https://github.com/Kitware/trame/pull/456
EDIT 2: same behavior as described above with validation/core/17_hot_reload.py

**To Reproduce**

1. Run the examples/validation/core_features/hot_reload.py examples
2. try to change stuff in controller function or state change listener
3. if does not work
4. try to change stuff in the UI definitions
5. it does not work

**Expected behavior**

The reload should happen correctly at runtime.

**Platform:**

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***
tested on both mac M1 and linux
- [ ] Windows
- [x] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [x] Chrome
- [x] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

**Comment by bourdaisj** [comment]
@psavery

**Comment by jourdain** [comment]
https://github.com/Kitware/trame-server/releases/tag/v2.16.1
