### ISSUE TITLE
How to implement custom frontend and remote view?

### ISSUE THREAD

**Issue by marospekarik** [Kitware/trame#458]
Hello, I am trying to utilize Trame as my backend service which processes and renders VTK on the server side. However, I want to initiate events from my specific frontend user interface (react), instead of from Vuetify on the server. Is there a method available that would allow me to stream solely the application window to my client?

**Comment by jourdain** [comment]
You can drive the full trame application from the outside by using some communication infrastructure available in [trame-iframe](https://github.com/Kitware/trame-iframe/tree/master/examples/js-trame)

HTH

**Comment by jourdain** [comment]
Side note, vuetify is not the only widget library trame expose you to. Trame really expose you to the full Vue.js ecosystem, therefore if you don't like Vuetify or Quasar you can pick any other one and integrate it in trame fairly easily and quickly.

**Comment by jourdain** [comment]
You are welcome! Have fun with trame...
