### ISSUE TITLE
Flushing layout content does not work if the template name has an underscore

### ISSUE THREAD

**Issue by landynfrancis** [Kitware/trame#465]
**Describe the bug**

My project involves having popup windows, and to implement this feature, I used separate app classes that each have their own `template_name`. They are accessed by going to URL `{ip_address}/index.html?ui={template_name}`. However, I noticed that if the `template_name` has an underscore character in it (and possibly other special characters), calling `layout.flush_content()` to force new content to the client has no effect.

**To Reproduce**

1. Copy the code attached to this issue
2. Run the file with python
3. Click "working" and "not working" (These will open up two almost identical pages in different tabs.)
4. In the "working" tab, click the "Test" button, the text "Yes" should change to "test 1", then increment as you continue to press the button.
5. In the "not working" tab, the same behavior does not change the text unless the page is refreshed.

The only difference in the two classes is the `template_name` passed to the `VAppLayout`

***Code***

```python
import trame.widgets.html as h
import trame.widgets.vuetify3 as v3
from trame.app import get_server
from trame.ui.vuetify3 import VAppLayout, SinglePageLayout


class Example2:
    def __init__(self, server=None):
        self.server = get_server(server, client_type="vue3")
        self.layout = self._build_ui()
        self.count = 0

    def _build_ui(self):
        with VAppLayout(self.server, template_name="example2") as layout:
            with layout:
                v3.VBtn("test (spoiler, I work)", style="background-color:gray;", click=self.test)
                with v3.VContainer() as self.div:
                    h.Div("YES")
        return layout

    def test(self):
        self.count += 1

        self.div.clear()
        with self.div:
            h.Div(f"test {self.count}")
        self.layout.flush_content()


class Example3:
    def __init__(self, server=None):
        self.server = get_server(server, client_type="vue3")
        self.layout = self._build_ui()
        self.count = 0

    def _build_ui(self):
        with VAppLayout(self.server, template_name="example_3") as layout:
            with layout:
                v3.VBtn("test (spoiler, I don't work)", style="background-color:gray;", click=self.test)
                with v3.VContainer() as self.div:
                    h.Div("YES")
        return layout

    def test(self):
        self.count += 1

        self.div.clear()
        with self.div:
            h.Div(f"test {self.count}")
        self.layout.flush_content()


class Example:
    def __init__(self, server=None):
        self.server = get_server(server, client_type="vue3")
        self.layout = self._build_ui()
        self.example2 = Example2()
        self.example3 = Example3()

    def _build_ui(self):
        with SinglePageLayout(self.server) as layout:
            with layout.toolbar:
                v3.VBtn("Not Working", click="window.open('/?ui=example_3', target='_blank')")
                v3.VBtn("Working", click="window.open('/?ui=example2', target='_blank')")


if __name__ == "__main__":
    app = Example()
    app.server.start()
```

**Expected behavior**

Ideally, `layout.flush_content()` should work regardless of the `template_name` used when creating the layout.

**Platform:**

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [x] Windows
- [ ] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS
(Linux running the server, Windows connecting through Chrome)

***Browsers Affected:***

- [x] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [ ] Brave
- [ ] IE 11

**Comment by jourdain** [comment]
Should be fixed with `trame-client==2.16.2`
