### ISSUE TITLE
vscode remote support on NERSC?

### ISSUE THREAD

**Issue by swelborn** [Kitware/trame#468]
**Describe the bug**

The example from https://kitware.github.io/trame/guide/deployment/jupyter.html does work in jupyter on my local machine (mac), both in jupyter and vscode.

![image](https://github.com/Kitware/trame/assets/55868530/988a58bd-2a7d-4578-bd2c-a477a69899db)

I am trying to test this out on NERSC through both NERSC's jupyterhub and vscode. It doesn't render in either. 

It is understandable that NERSC's jupyterhub -- I have had issues rendering widgets from third parties (e.g., bqplot widgets are not registered with the jupyterlab instance they are running on the hub, and so they can't render there). Ideally it would work there, though.

However, I'm unsure why it wouldn't work through vscode. I have tried two routes:
1. Select python from conda env binary as kernel:
![Screenshot 2024-03-03 at 12 24 09 PM](https://github.com/Kitware/trame/assets/55868530/e63b59f2-3bd2-4435-8e4e-ca68207e396a)

2. Select existing jupyterlab instance after registering test-trame-py312 in available kernels:
```bash
conda activate test-trame-py312
python -m ipykernel install --user --name test-trame-312 --display-name trame-312
jupyter lab --ip=$(hostname -i) --no-browser
```

Connect to this jupyterlab server:
![Screenshot 2024-03-03 at 12 33 03 PM](https://github.com/Kitware/trame/assets/55868530/7dbc31a9-63a4-4119-9a86-ff26b6b0c99b)

Select "Existing jupyter server"
![Screenshot 2024-03-03 at 12 33 39 PM](https://github.com/Kitware/trame/assets/55868530/1e112374-6acd-4c6d-80ce-fe51b4e7df7d)

When I connect to the server through vscode, I see that it is starting the kernel`[I 2024-03-03 09:30:49.879 ServerApp] Kernel started:`

and I can import trame, etc. When I run the example (cone) I don't get a render. You can see that it shows the first output line ('new resolution 6'), but no cone:
![image](https://github.com/Kitware/trame/assets/55868530/37dc17f7-67c2-4e88-81e0-4205735e555e)

even though `--log-level=DEBUG` on the jupyterlab instance shows that display_data is executing in the UI output cell.
```
[D 2024-03-03 09:57:05.401 ServerApp] activity on ce38639c-6f47-4945-989a-a0155fc68859: status (busy)
[D 2024-03-03 09:57:05.402 ServerApp] activity on ce38639c-6f47-4945-989a-a0155fc68859: execute_input
[D 2024-03-03 09:57:05.498 ServerApp] activity on ce38639c-6f47-4945-989a-a0155fc68859: stream
[D 2024-03-03 09:57:05.498 ServerApp] activity on ce38639c-6f47-4945-989a-a0155fc68859: display_data
[D 2024-03-03 09:57:05.501 ServerApp] activity on ce38639c-6f47-4945-989a-a0155fc68859: status (idle)
```

I also tried this with python=3.10 to no avail. 

Unsure how to further debug. Let me know if you can reproduce, would be good to know if it is something with NERSC environment that is causing this. 

**Install commands**

```bash
ssh perlmutter
conda create -n test-trame-py312 python=3.12
conda activate test-trame-py312
pip install trame
pip install trame-vuetify trame-vtk
pip install vtk
pip install jupyterlab
pip install ipykernel
```

**Expected behavior**

To be able to run on a remote host through vscode's jupyter support. 

**Platform:**

***OS:***
- [ x ] Linux

**Comment by jourdain** [comment]
The issue is related that on a remote setup not all the port might be open (as opposed to locally) so you need to either use __trame-jupyter-extension__ or the server proxy of jupyter.

When the extension is available, it will be automatically detected and use the existing JupyterComm instead of its own WebSocket endpoint.

But if you are using JupyterHub and you have the server-proxy installed you can let trame know to use it instead of relying on its own direct server URL. 

So the idea will be to do the following

```python
app = Cone()
await app.ui.ready
app.ui.iframe_builder = "jupyter-hub" # Available options: serverproxy, jupyter-extension, jupyter-hub
app.ui
```

If that does not work, you have other controls to fine-tune the iframe URL, but that will depend on your setup and it might not be easy to explain what you should do without seeing the runtime environment.

**Comment by swelborn** [comment]
I am not having any luck using any of the available options in your list, and I cannot add a labextension to the shared jupyterhub at nersc. 

When I do "jupyter-hub", I get a 404 that takes me back to our entrypoint to the hub if I click control panel:
![image](https://github.com/Kitware/trame/assets/55868530/be38e59f-2479-48e0-a5b3-6e69a381abd3)

I can make recursive jupyterlab logins but that is not very helpful.

"serverproxy" yields nothing:
![image](https://github.com/Kitware/trame/assets/55868530/c26264d1-f826-416e-b444-de4dd6b8dea9)

This is the URL I am connected to when I log into jupyterhub, maybe this helps?

`https://jupyter.nersc.gov/user/swelborn/perlmutter-login-node-base/lab/tree/global/homes/s/swelborn/gits/trame-test-py312/examples/jupyter/show.ipynb`

I did get this to work on vscode remote by asking what the port was and adding it to my list of forwarded ports. I'm assuming you could pass in a trame_server.Server instance into the MyTrameApp constructor to set up preconfigured ports, etc. 

![image](https://github.com/Kitware/trame/assets/55868530/df0b69f5-5295-41ab-88f1-026222798385)

**Comment by jourdain** [comment]
So it seems that [jupyter-server-proxy](https://jupyter-server-proxy.readthedocs.io/en/latest/) is not available. Unless I know more about what's available and how trame can leverage the existing infrastructure, I won't be of much help.

**Comment by swelborn** [comment]
ok! i will ask someone who knows the answer and get back to you.

**Comment by swelborn** [comment]
We have jupyter server proxy installed/enabled, but we have named servers. Thus we have a prefix to make my server run at: `https://jupyter.nersc.gov/user/swelborn/perlmutter-login-node-base`

For our dask dashboard, we have to do something like this `"{JUPYTERHUB_SERVICE_PREFIX}proxy/{host}:{port}/status"`

Does this help?

**Comment by jourdain** [comment]
Do you know how you can get `{host}`?

**Comment by jourdain** [comment]
We finally got a chance to test it on NERSC and the issue was with our __"jupyter-hub"__ implementation, we were generating 2 slash in a row. The latest version of __"trame-client>=2.17.1"__ is now fixing it.

On top of that, it should automatically detect the jupyter-hub environment so you should not need to set the __iframe_builder__ at all.

And in case I've also added a __jupyter-hub-host__ option.
