### ISSUE TITLE
remoteview on windows 11 cant work correctly

### ISSUE THREAD

**Issue by ylwbl** [Kitware/trame#469]
I use the official examples, and try to use vtkRmoteView instead of vtkLocalView,but it cant work correctly, when I press and drag the model with the left mouse button,the ws broke like this but if I use vtkLocalView, it works correctly.
  
![1709611373844](https://github.com/Kitware/trame/assets/38969394/67ac3a13-ee84-4fff-ae63-fb999cfb1b00)
![1709611389371](https://github.com/Kitware/trame/assets/38969394/badfadef-13c2-4970-850a-480c753dfced)

The following is code

```python
renderer = vtkRenderer()
renderWindow = vtkRenderWindow()
renderWindow.AddRenderer(renderer)

renderWindowInteractor = vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
renderWindowInteractor.GetInteractorStyle().SetCurrentStyleToTrackballCamera()

cone_source = vtkConeSource()
mapper = vtkPolyDataMapper()
mapper.SetInputConnection(cone_source.GetOutputPort())
actor = vtkActor()
actor.SetMapper(mapper)

renderer.AddActor(actor)
renderer.ResetCamera()

server = get_server()
server.client_type = "vue2"
ctrl = server.controller

with SinglePageLayout(server) as layout:
    layout.title.set_text("Hello trame")

    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            view = vtk.VtkRemoteLocalView(renderWindow)

if __name__ == "__main__":
    server.start()

```

and this is the package version I used

```
trame==3.3.0
trame-client==2.14.2
trame-server==2.14.0
trame-vtk==2.6.3
```

**Comment by jourdain** [comment]
This is really strange. 

Can you provide more information?
- vtk version
- python / conda
- os
- anything else that could be of interest

**Comment by ylwbl** [comment]
- vtk version 9.3.0
- python: 3.10.0 but I also have try 3.9.0
- os  windows11  professional  22621.2715
- gpu and gpu driver NVIDIA GeForce RTX 2060 with Max-Q Design 30.0.15.1278
I have try the same python file at my another laptop,this notebook does not have a stand-alone video card. It uses an integrated video card.and its running well

**Comment by jourdain** [comment]
Hum, not easy to tell but it could be a driver issue. Does ParaView works on that Window machine?

**Comment by jourdain** [comment]
Closing since it seems to be a driver issue
