### ISSUE TITLE
Combine with 3Dslicer

### ISSUE THREAD

**Issue by zhuczhuc** [Kitware/trame#590]
Does is possible combine trame with 3Dslicer windows? It will make our work more simple, I think.

**Comment by finetjul** [comment]
Hi @zhuczhuc, we are working on it... Please reach out to me for more information.

**Comment by zhuczhuc** [comment]
Looking forward!

**Comment by zhuczhuc** [comment]
> Hi @zhuczhuc, we are working on it... Please reach out to me for more information.

Looking forward!
