### ISSUE TITLE
image missing

### ISSUE THREAD

**Issue by puiseux** [Kitware/trame#79]
**Describe the bug**

referenced in [https://github.com/Kitware/trame/tree/master/examples/03_markdown](https://github.com/Kitware/trame/tree/master/examples/03_markdown)
this image is missing [https://github.com/Kitware/trame/blob/docs/content/examples/Markdown.jpg](https://github.com/Kitware/trame/blob/docs/content/examples/Markdown.jpg)
**To Reproduce**

1. Go to 'https://github.com/Kitware/trame/tree/master/examples/03_markdown'
2. Click on 'https://github.com/Kitware/trame/blob/docs/content/examples/Markdown.jpg'
3. See error

**Comment by jourdain** [comment]
Thanks for the report. Should be fixed now.
