### ISSUE TITLE
How to pre-determine which vtkReader to use for vtk files

### ISSUE THREAD

**Issue by chenjiajun1991** [Kitware/trame#97]
### Discussed in https://github.com/Kitware/trame/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **chenjiajun1991** July 13, 2022</sup>
I need to load multiple types of vtk files, can I pre-determine what type vtk belongs to,and pre-pick the appropriate vtkReader.</div>

**Comment by jourdain** [comment]
Liked described in #92, you can easily managed it on your application side.
